///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Hackaton
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BuyProduct recording.
    /// </summary>
    [TestModule("82fbf51f-d5db-4bfa-a6af-2dd7cdb2669e", ModuleType.Recording, 1)]
    public partial class BuyProduct : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HackatonRepository repository.
        /// </summary>
        public static HackatonRepository repo = HackatonRepository.Instance;

        static BuyProduct instance = new BuyProduct();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BuyProduct()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BuyProduct Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'com.hackaton.epam.tahackaton' on device 'emulator-5554'.", new RecordItemIndex(0));
            Host.Local.RunMobileApp("emulator-5554", "com.hackaton.epam.tahackaton", true);
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'hackaton.epam.ta@gmail.com' on item 'ComHackatonEpamTahackaton.LoginForm.Email'.", repo.ComHackatonEpamTahackaton.LoginForm.EmailInfo, new RecordItemIndex(1));
            repo.ComHackatonEpamTahackaton.LoginForm.Email.Element.SetAttributeValue("Text", "hackaton.epam.ta@gmail.com");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '21wqsaxz' on item 'ComHackatonEpamTahackaton.LoginForm.Password'.", repo.ComHackatonEpamTahackaton.LoginForm.PasswordInfo, new RecordItemIndex(2));
            repo.ComHackatonEpamTahackaton.LoginForm.Password.Element.SetAttributeValue("Text", "21wqsaxz");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHackatonEpamTahackaton.LoginForm.EmailSignInButton' at 586;39", repo.ComHackatonEpamTahackaton.LoginForm.EmailSignInButtonInfo, new RecordItemIndex(3));
            repo.ComHackatonEpamTahackaton.LoginForm.EmailSignInButton.Touch("586;39");
            Delay.Milliseconds(1000);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHackatonEpamTahackaton.BskImgThird' at 105;127", repo.ComHackatonEpamTahackaton.BskImgThirdInfo, new RecordItemIndex(4));
            repo.ComHackatonEpamTahackaton.BskImgThird.Touch("105;127");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHackatonEpamTahackaton.CartPlus' at 20;45", repo.ComHackatonEpamTahackaton.CartPlusInfo, new RecordItemIndex(5));
            repo.ComHackatonEpamTahackaton.CartPlus.Touch("20;45");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHackatonEpamTahackaton.PayNow' at 466;65", repo.ComHackatonEpamTahackaton.PayNowInfo, new RecordItemIndex(6));
            repo.ComHackatonEpamTahackaton.PayNow.Touch("466;65");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'ComHackatonEpamTahackaton.CartActivity'.", repo.ComHackatonEpamTahackaton.CartActivityInfo, new RecordItemIndex(7));
            repo.ComHackatonEpamTahackaton.CartActivity.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
