///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Hackaton
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the HackatonRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("d62d42c1-62cf-425e-8c2b-a70bf130eabe")]
    public partial class HackatonRepository : RepoGenBaseFolder
    {
        static HackatonRepository instance = new HackatonRepository();
        HackatonRepositoryFolders.ComHackatonEpamTahackatonAppFolder _comhackatonepamtahackaton;

        /// <summary>
        /// Gets the singleton class instance representing the HackatonRepository element repository.
        /// </summary>
        [RepositoryFolder("d62d42c1-62cf-425e-8c2b-a70bf130eabe")]
        public static HackatonRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public HackatonRepository() 
            : base("HackatonRepository", "/", null, 0, false, "d62d42c1-62cf-425e-8c2b-a70bf130eabe", ".\\RepositoryImages\\HackatonRepositoryd62d42c1.rximgres")
        {
            _comhackatonepamtahackaton = new HackatonRepositoryFolders.ComHackatonEpamTahackatonAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d62d42c1-62cf-425e-8c2b-a70bf130eabe")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComHackatonEpamTahackaton folder.
        /// </summary>
        [RepositoryFolder("a583aa08-5ded-4692-8ca6-8a3510f248d8")]
        public virtual HackatonRepositoryFolders.ComHackatonEpamTahackatonAppFolder ComHackatonEpamTahackaton
        {
            get { return _comhackatonepamtahackaton; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class HackatonRepositoryFolders
    {
        /// <summary>
        /// The ComHackatonEpamTahackatonAppFolder folder.
        /// </summary>
        [RepositoryFolder("a583aa08-5ded-4692-8ca6-8a3510f248d8")]
        public partial class ComHackatonEpamTahackatonAppFolder : RepoGenBaseFolder
        {
            HackatonRepositoryFolders.LoginFormFolder _loginform;
            RepoItemInfo _loginactivityInfo;
            BskImgThirdInfoClass _bskimgthirdInfo;
            CartProductInfoClass _cartproductInfo;
            RepoItemInfo _cartminusInfo;
            RepoItemInfo _errorcountInfo;
            RepoItemInfo _cartplusInfo;
            RepoItemInfo _cartbtnInfo;
            RepoItemInfo _comgoogleandroidlibrariesyoutubeplaInfo;
            RepoItemInfo _pausevideoInfo;
            RepoItemInfo _paynowInfo;
            RepoItemInfo _contactusInfo;
            RepoItemInfo _wrapInfo;
            RepoItemInfo _cartactivityInfo;
            RepoItemInfo _contactusactivityInfo;
            RepoItemInfo _youtubeplayeractivityInfo;
            RepoItemInfo _rstringerrorinvalidemailInfo;
            RepoItemInfo _bskimgsecondInfo;
            RepoItemInfo _linearInfo;

            /// <summary>
            /// Creates a new ComHackatonEpamTahackaton  folder.
            /// </summary>
            public ComHackatonEpamTahackatonAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComHackatonEpamTahackaton", "/mobileapp[@title='com.hackaton.epam.tahackaton']", parentFolder, 30000, null, false, "a583aa08-5ded-4692-8ca6-8a3510f248d8", "")
            {
                _loginform = new HackatonRepositoryFolders.LoginFormFolder(this);
                _loginactivityInfo = new RepoItemInfo(this, "LoginActivity", "form[@title='LoginActivity']", 30000, null, "99132ead-41f0-4fff-a9be-1b9c1a38b7ec");
                _bskimgthirdInfo = new BskImgThirdInfoClass(this);
                _cartproductInfo = new CartProductInfoClass(this);
                _cartminusInfo = new RepoItemInfo(this, "CartMinus", "form[@title='CartActivity']/androidelement[@rid='content']//container[@containertype='Linear']/container[3]/picture[@resourceid='R.drawable.cart_activity_minus']", 30000, null, "54551b21-4b1c-4c53-b32d-52245ee1ab9c");
                _errorcountInfo = new RepoItemInfo(this, "ErrorCount", "form[@title='CartActivity']/androidelement[@rid='content']//container[@containertype='Linear']/container[2]/text[@rid='error_count']", 30000, null, "70721426-6d17-4584-a9e2-f8ca11098180");
                _cartplusInfo = new RepoItemInfo(this, "CartPlus", "form[@title='CartActivity']/androidelement[@rid='content']//container[@containertype='Linear']/container[3]/picture[@resourceid='R.drawable.cart_activity_plus']", 30000, null, "5237e4e9-033c-4b99-a7c8-744d5167df0c");
                _cartbtnInfo = new RepoItemInfo(this, "CartBtn", "form[@title='CartActivity']/androidelement[@rid='content']//container[@containertype='Linear']/container[@containertype='Relative']/picture[@resourceid='R.drawable.cart_activity_play_btn']", 30000, null, "41609964-a36c-4d4a-907f-8d6220e5dc8b");
                _comgoogleandroidlibrariesyoutubeplaInfo = new RepoItemInfo(this, "ComGoogleAndroidLibrariesYoutubePla", "form[@title='(none)']/container[@rid='content']/container/androidelement/androidelement[5]/androidelement/container[@containertype='Relative']/container[@containertype='Relative']/container[2]/androidelement[2]", 30000, null, "883c4698-40b2-44c7-868b-9c9f17730a84");
                _pausevideoInfo = new RepoItemInfo(this, "PauseVideo", "form[@title='(none)']/container[@rid='content']/container/androidelement/androidelement[5]//picture[@contentdescription='Pause video']", 30000, null, "b3f5b1c3-3540-4025-8c87-42e6fdb616ca");
                _paynowInfo = new RepoItemInfo(this, "PayNow", "form[@title='CartActivity']/androidelement[@rid='content']//button[@resourceid='R.string.payNow']", 30000, null, "5133b6e2-1637-41fe-b47b-1ff082581a3b");
                _contactusInfo = new RepoItemInfo(this, "ContactUs", "form[@title='CartActivity']/androidelement[@rid='content']//text[@rid='contactUs']", 30000, null, "cc332eca-0c7c-4655-868f-c4f16e8991b0");
                _wrapInfo = new RepoItemInfo(this, "Wrap", "form[@title='ContactUsActivity']/?/?/dom[@domain='www.epam.com']/body/div[1]/div[3]/div[2]/div/div/div/div[2]/div/div/div[1]/div/div[1]", 30000, null, "b2b1f474-fbfa-419f-879f-c2fd5dacc78f");
                _cartactivityInfo = new RepoItemInfo(this, "CartActivity", "form[@title='CartActivity']", 30000, null, "04b6d882-d24e-40cc-a987-950b64334be0");
                _contactusactivityInfo = new RepoItemInfo(this, "ContactUsActivity", "form[@title='ContactUsActivity']", 30000, null, "e709e8a0-32a8-480e-92a4-4dc4a472a043");
                _youtubeplayeractivityInfo = new RepoItemInfo(this, "YoutubePlayerActivity", "form[@title='YoutubePlayerActivity']", 30000, null, "bf76e304-64a1-4715-8b0a-bf5d51f16606");
                _rstringerrorinvalidemailInfo = new RepoItemInfo(this, "RStringErrorInvalidEmail", "?/?/text[@resourceid='R.string.error_invalid_email']", 30000, null, "b294b645-3a0d-4d17-baad-0882a9a9cb08");
                _bskimgsecondInfo = new RepoItemInfo(this, "BskImgSecond", "form[@title='BasketActivity']/androidelement[@rid='content']//picture[@resourceid='R.drawable.basket_activity_second_product']", 30000, null, "10a46dfd-f5b1-4976-b298-315c855b02e8");
                _linearInfo = new RepoItemInfo(this, "Linear", "form[@title='CartActivity']/androidelement[@rid='content']//container[@containertype='Linear']/container[2]", 30000, null, "2f38f71d-f1cc-4a22-ba20-e64786a36590");
            }

            /// <summary>
            /// The BskImgThirdInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("59a4580f-504e-422d-85a6-937b558f2068")]
            public class BskImgThirdInfoClass : RepoItemInfo
            {
                /// <summary>
                /// BskImgThirdInfoClass class constructor.
                /// </summary>
                public BskImgThirdInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "BskImgThird", "form[@title='BasketActivity']/androidelement[@rid='content']//picture[@resourceid='R.drawable.basket_activity_third_product']", 30000, null, "59a4580f-504e-422d-85a6-937b558f2068")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("1852f340-8701-4f93-80d2-43bb897480f6")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("1852f340-8701-4f93-80d2-43bb897480f6");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("1852f340-8701-4f93-80d2-43bb897480f6")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("1852f340-8701-4f93-80d2-43bb897480f6", cropRect);
                }
            }

            /// <summary>
            /// The CartProductInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("3b5aede5-9264-4fd6-8f78-14510f7bd741")]
            public class CartProductInfoClass : RepoItemInfo
            {
                /// <summary>
                /// CartProductInfoClass class constructor.
                /// </summary>
                public CartProductInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "CartProduct", "form[@title='CartActivity']/androidelement[@rid='content']//picture[@resourceid='R.drawable.basket_activity_third_product']", 30000, null, "3b5aede5-9264-4fd6-8f78-14510f7bd741")
                { }

                /// <summary>
                /// Gets the packScreen1 item image.
                /// </summary>
                /// <returns>The packScreen1 image.</returns>
                [RepositoryImage("c61cc47b-c5fd-464b-90ce-a0e453bc2b84")]
                public CompressedImage GetpackScreen1()
                {
                    return GetImage("c61cc47b-c5fd-464b-90ce-a0e453bc2b84");
                }

                /// <summary>
                /// Gets the packScreen1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("c61cc47b-c5fd-464b-90ce-a0e453bc2b84")]
                public CompressedImage GetpackScreen1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("c61cc47b-c5fd-464b-90ce-a0e453bc2b84", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a583aa08-5ded-4692-8ca6-8a3510f248d8")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a583aa08-5ded-4692-8ca6-8a3510f248d8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginActivity item.
            /// </summary>
            [RepositoryItem("99132ead-41f0-4fff-a9be-1b9c1a38b7ec")]
            public virtual Ranorex.Form LoginActivity
            {
                get
                {
                    return _loginactivityInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The LoginActivity item info.
            /// </summary>
            [RepositoryItemInfo("99132ead-41f0-4fff-a9be-1b9c1a38b7ec")]
            public virtual RepoItemInfo LoginActivityInfo
            {
                get
                {
                    return _loginactivityInfo;
                }
            }

            /// <summary>
            /// The BskImgThird item.
            /// </summary>
            [RepositoryItem("59a4580f-504e-422d-85a6-937b558f2068")]
            public virtual Ranorex.Picture BskImgThird
            {
                get
                {
                    return _bskimgthirdInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The BskImgThird item info.
            /// </summary>
            [RepositoryItemInfo("59a4580f-504e-422d-85a6-937b558f2068")]
            public virtual BskImgThirdInfoClass BskImgThirdInfo
            {
                get
                {
                    return _bskimgthirdInfo;
                }
            }

            /// <summary>
            /// The CartProduct item.
            /// </summary>
            [RepositoryItem("3b5aede5-9264-4fd6-8f78-14510f7bd741")]
            public virtual Ranorex.Picture CartProduct
            {
                get
                {
                    return _cartproductInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The CartProduct item info.
            /// </summary>
            [RepositoryItemInfo("3b5aede5-9264-4fd6-8f78-14510f7bd741")]
            public virtual CartProductInfoClass CartProductInfo
            {
                get
                {
                    return _cartproductInfo;
                }
            }

            /// <summary>
            /// The CartMinus item.
            /// </summary>
            [RepositoryItem("54551b21-4b1c-4c53-b32d-52245ee1ab9c")]
            public virtual Ranorex.Picture CartMinus
            {
                get
                {
                    return _cartminusInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The CartMinus item info.
            /// </summary>
            [RepositoryItemInfo("54551b21-4b1c-4c53-b32d-52245ee1ab9c")]
            public virtual RepoItemInfo CartMinusInfo
            {
                get
                {
                    return _cartminusInfo;
                }
            }

            /// <summary>
            /// The ErrorCount item.
            /// </summary>
            [RepositoryItem("70721426-6d17-4584-a9e2-f8ca11098180")]
            public virtual Ranorex.Text ErrorCount
            {
                get
                {
                    return _errorcountInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ErrorCount item info.
            /// </summary>
            [RepositoryItemInfo("70721426-6d17-4584-a9e2-f8ca11098180")]
            public virtual RepoItemInfo ErrorCountInfo
            {
                get
                {
                    return _errorcountInfo;
                }
            }

            /// <summary>
            /// The CartPlus item.
            /// </summary>
            [RepositoryItem("5237e4e9-033c-4b99-a7c8-744d5167df0c")]
            public virtual Ranorex.Picture CartPlus
            {
                get
                {
                    return _cartplusInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The CartPlus item info.
            /// </summary>
            [RepositoryItemInfo("5237e4e9-033c-4b99-a7c8-744d5167df0c")]
            public virtual RepoItemInfo CartPlusInfo
            {
                get
                {
                    return _cartplusInfo;
                }
            }

            /// <summary>
            /// The CartBtn item.
            /// </summary>
            [RepositoryItem("41609964-a36c-4d4a-907f-8d6220e5dc8b")]
            public virtual Ranorex.Picture CartBtn
            {
                get
                {
                    return _cartbtnInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The CartBtn item info.
            /// </summary>
            [RepositoryItemInfo("41609964-a36c-4d4a-907f-8d6220e5dc8b")]
            public virtual RepoItemInfo CartBtnInfo
            {
                get
                {
                    return _cartbtnInfo;
                }
            }

            /// <summary>
            /// The ComGoogleAndroidLibrariesYoutubePla item.
            /// </summary>
            [RepositoryItem("883c4698-40b2-44c7-868b-9c9f17730a84")]
            public virtual Ranorex.AndroidElement ComGoogleAndroidLibrariesYoutubePla
            {
                get
                {
                    return _comgoogleandroidlibrariesyoutubeplaInfo.CreateAdapter<Ranorex.AndroidElement>(true);
                }
            }

            /// <summary>
            /// The ComGoogleAndroidLibrariesYoutubePla item info.
            /// </summary>
            [RepositoryItemInfo("883c4698-40b2-44c7-868b-9c9f17730a84")]
            public virtual RepoItemInfo ComGoogleAndroidLibrariesYoutubePlaInfo
            {
                get
                {
                    return _comgoogleandroidlibrariesyoutubeplaInfo;
                }
            }

            /// <summary>
            /// The PauseVideo item.
            /// </summary>
            [RepositoryItem("b3f5b1c3-3540-4025-8c87-42e6fdb616ca")]
            public virtual Ranorex.Picture PauseVideo
            {
                get
                {
                    return _pausevideoInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PauseVideo item info.
            /// </summary>
            [RepositoryItemInfo("b3f5b1c3-3540-4025-8c87-42e6fdb616ca")]
            public virtual RepoItemInfo PauseVideoInfo
            {
                get
                {
                    return _pausevideoInfo;
                }
            }

            /// <summary>
            /// The PayNow item.
            /// </summary>
            [RepositoryItem("5133b6e2-1637-41fe-b47b-1ff082581a3b")]
            public virtual Ranorex.Button PayNow
            {
                get
                {
                    return _paynowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PayNow item info.
            /// </summary>
            [RepositoryItemInfo("5133b6e2-1637-41fe-b47b-1ff082581a3b")]
            public virtual RepoItemInfo PayNowInfo
            {
                get
                {
                    return _paynowInfo;
                }
            }

            /// <summary>
            /// The ContactUs item.
            /// </summary>
            [RepositoryItem("cc332eca-0c7c-4655-868f-c4f16e8991b0")]
            public virtual Ranorex.Text ContactUs
            {
                get
                {
                    return _contactusInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContactUs item info.
            /// </summary>
            [RepositoryItemInfo("cc332eca-0c7c-4655-868f-c4f16e8991b0")]
            public virtual RepoItemInfo ContactUsInfo
            {
                get
                {
                    return _contactusInfo;
                }
            }

            /// <summary>
            /// The Wrap item.
            /// </summary>
            [RepositoryItem("b2b1f474-fbfa-419f-879f-c2fd5dacc78f")]
            public virtual Ranorex.DivTag Wrap
            {
                get
                {
                    return _wrapInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Wrap item info.
            /// </summary>
            [RepositoryItemInfo("b2b1f474-fbfa-419f-879f-c2fd5dacc78f")]
            public virtual RepoItemInfo WrapInfo
            {
                get
                {
                    return _wrapInfo;
                }
            }

            /// <summary>
            /// The CartActivity item.
            /// </summary>
            [RepositoryItem("04b6d882-d24e-40cc-a987-950b64334be0")]
            public virtual Ranorex.Form CartActivity
            {
                get
                {
                    return _cartactivityInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The CartActivity item info.
            /// </summary>
            [RepositoryItemInfo("04b6d882-d24e-40cc-a987-950b64334be0")]
            public virtual RepoItemInfo CartActivityInfo
            {
                get
                {
                    return _cartactivityInfo;
                }
            }

            /// <summary>
            /// The ContactUsActivity item.
            /// </summary>
            [RepositoryItem("e709e8a0-32a8-480e-92a4-4dc4a472a043")]
            public virtual Ranorex.Form ContactUsActivity
            {
                get
                {
                    return _contactusactivityInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The ContactUsActivity item info.
            /// </summary>
            [RepositoryItemInfo("e709e8a0-32a8-480e-92a4-4dc4a472a043")]
            public virtual RepoItemInfo ContactUsActivityInfo
            {
                get
                {
                    return _contactusactivityInfo;
                }
            }

            /// <summary>
            /// The YoutubePlayerActivity item.
            /// </summary>
            [RepositoryItem("bf76e304-64a1-4715-8b0a-bf5d51f16606")]
            public virtual Ranorex.Form YoutubePlayerActivity
            {
                get
                {
                    return _youtubeplayeractivityInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The YoutubePlayerActivity item info.
            /// </summary>
            [RepositoryItemInfo("bf76e304-64a1-4715-8b0a-bf5d51f16606")]
            public virtual RepoItemInfo YoutubePlayerActivityInfo
            {
                get
                {
                    return _youtubeplayeractivityInfo;
                }
            }

            /// <summary>
            /// The RStringErrorInvalidEmail item.
            /// </summary>
            [RepositoryItem("b294b645-3a0d-4d17-baad-0882a9a9cb08")]
            public virtual Ranorex.Text RStringErrorInvalidEmail
            {
                get
                {
                    return _rstringerrorinvalidemailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RStringErrorInvalidEmail item info.
            /// </summary>
            [RepositoryItemInfo("b294b645-3a0d-4d17-baad-0882a9a9cb08")]
            public virtual RepoItemInfo RStringErrorInvalidEmailInfo
            {
                get
                {
                    return _rstringerrorinvalidemailInfo;
                }
            }

            /// <summary>
            /// The BskImgSecond item.
            /// </summary>
            [RepositoryItem("10a46dfd-f5b1-4976-b298-315c855b02e8")]
            public virtual Ranorex.Picture BskImgSecond
            {
                get
                {
                    return _bskimgsecondInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The BskImgSecond item info.
            /// </summary>
            [RepositoryItemInfo("10a46dfd-f5b1-4976-b298-315c855b02e8")]
            public virtual RepoItemInfo BskImgSecondInfo
            {
                get
                {
                    return _bskimgsecondInfo;
                }
            }

            /// <summary>
            /// The Linear item.
            /// </summary>
            [RepositoryItem("2f38f71d-f1cc-4a22-ba20-e64786a36590")]
            public virtual Ranorex.Container Linear
            {
                get
                {
                    return _linearInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Linear item info.
            /// </summary>
            [RepositoryItemInfo("2f38f71d-f1cc-4a22-ba20-e64786a36590")]
            public virtual RepoItemInfo LinearInfo
            {
                get
                {
                    return _linearInfo;
                }
            }

            /// <summary>
            /// The LoginForm folder.
            /// </summary>
            [RepositoryFolder("8cf8d0f6-687f-40f0-ad63-77894651fd80")]
            public virtual HackatonRepositoryFolders.LoginFormFolder LoginForm
            {
                get { return _loginform; }
            }
        }

        /// <summary>
        /// The LoginFormFolder folder.
        /// </summary>
        [RepositoryFolder("8cf8d0f6-687f-40f0-ad63-77894651fd80")]
        public partial class LoginFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _emailsigninbuttonInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _passwordInfo;

            /// <summary>
            /// Creates a new LoginForm  folder.
            /// </summary>
            public LoginFormFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginForm", "form[@title='LoginActivity']//container[@rid='login_form']", parentFolder, 30000, null, false, "8cf8d0f6-687f-40f0-ad63-77894651fd80", "")
            {
                _emailsigninbuttonInfo = new RepoItemInfo(this, "EmailSignInButton", "?/?/button[@resourceid='R.string.action_sign_in']", 30000, null, "0f08e390-1639-4100-af32-adf3c0a97998");
                _emailInfo = new RepoItemInfo(this, "Email", "container[@rid='email_login_form']//text[@rid='email']", 30000, null, "4740653e-fc11-4d29-8073-37f9c1c963f2");
                _passwordInfo = new RepoItemInfo(this, "Password", "container[@rid='email_login_form']//text[@rid='password']", 30000, null, "a6072ce7-899e-4500-85f2-3d78429969ce");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8cf8d0f6-687f-40f0-ad63-77894651fd80")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8cf8d0f6-687f-40f0-ad63-77894651fd80")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EmailSignInButton item.
            /// </summary>
            [RepositoryItem("0f08e390-1639-4100-af32-adf3c0a97998")]
            public virtual Ranorex.Button EmailSignInButton
            {
                get
                {
                    return _emailsigninbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EmailSignInButton item info.
            /// </summary>
            [RepositoryItemInfo("0f08e390-1639-4100-af32-adf3c0a97998")]
            public virtual RepoItemInfo EmailSignInButtonInfo
            {
                get
                {
                    return _emailsigninbuttonInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("4740653e-fc11-4d29-8073-37f9c1c963f2")]
            public virtual Ranorex.Text Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("4740653e-fc11-4d29-8073-37f9c1c963f2")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("a6072ce7-899e-4500-85f2-3d78429969ce")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("a6072ce7-899e-4500-85f2-3d78429969ce")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}