///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Hackaton
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Video recording.
    /// </summary>
    [TestModule("145f4e0a-609e-4a4f-90f0-8303efb20cda", ModuleType.Recording, 1)]
    public partial class Video : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HackatonRepository repository.
        /// </summary>
        public static HackatonRepository repo = HackatonRepository.Instance;

        static Video instance = new Video();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Video()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Video Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHackatonEpamTahackaton.BskImgThird' at 25;252", repo.ComHackatonEpamTahackaton.BskImgThirdInfo, new RecordItemIndex(0));
            repo.ComHackatonEpamTahackaton.BskImgThird.Touch("25;252");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHackatonEpamTahackaton.CartBtn' at 491;93", repo.ComHackatonEpamTahackaton.CartBtnInfo, new RecordItemIndex(1));
            repo.ComHackatonEpamTahackaton.CartBtn.Touch("491;93");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHackatonEpamTahackaton.ComGoogleAndroidLibrariesYoutubePla' at 1603;91", repo.ComHackatonEpamTahackaton.ComGoogleAndroidLibrariesYoutubePlaInfo, new RecordItemIndex(2));
            repo.ComHackatonEpamTahackaton.ComGoogleAndroidLibrariesYoutubePla.Touch("1603;91");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHackatonEpamTahackaton.PauseVideo' at 98;99", repo.ComHackatonEpamTahackaton.PauseVideoInfo, new RecordItemIndex(3));
            repo.ComHackatonEpamTahackaton.PauseVideo.Touch("98;99");
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
